# Generated by Django 5.0.6 on 2025-12-17 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAnalysisLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ts_code", models.CharField(max_length=20, verbose_name="股票代码")),
                (
                    "stock_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="股票名称"
                    ),
                ),
                ("analysis_content", models.TextField(verbose_name="分析内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分析时间"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(unique=True, verbose_name="用户ID")),
                (
                    "ai_api_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="AI API Key"
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True,
                        default="deepseek-chat",
                        max_length=50,
                        null=True,
                        verbose_name="AI Model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                ("ts_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("user_id", "ts_code")},
            },
        ),
    ]
