# Generated by Django 5.0.6 on 2025-12-18 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                ("name", models.CharField(max_length=100, verbose_name="分组名称")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("user_id", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="api.watchlistgroup",
                verbose_name="所属分组",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user_id", "group", "ts_code")},
        ),
    ]
