# Generated by Django 5.0.6 on 2025-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=20, verbose_name="股票代码")),
                (
                    "stock_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="股票名称"
                    ),
                ),
                ("analysis_content", models.TextField(verbose_name="分析内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分析时间"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
