# Generated by Django 5.0.6 on 2025-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_watchlistgroup_alter_watchlist_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_base_url",
            field=models.CharField(
                blank=True,
                default="https://api.deepseek.com",
                max_length=255,
                null=True,
                verbose_name="AI Base URL",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                default="deepseek",
                max_length=50,
                null=True,
                verbose_name="AI Provider",
            ),
        ),
    ]

