# Generated by Django 5.0.6 on 2025-12-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_model",
            field=models.CharField(
                blank=True,
                default="deepseek-chat",
                max_length=50,
                null=True,
                verbose_name="AI Model",
            ),
        ),
    ]
