# Generated by Django 5.0.6 on 2025-12-21 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile_ai_base_url_ai_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                ("symbol", models.CharField(max_length=20, verbose_name="标的代码")),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "event_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="事件类型"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="来源"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="来源链接"
                    ),
                ),
                (
                    "license_status",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="许可状态"
                    ),
                ),
                (
                    "evidence",
                    models.TextField(blank=True, null=True, verbose_name="证据片段"),
                ),
                ("event_time", models.DateTimeField(verbose_name="事件时间")),
                (
                    "market_effective_time",
                    models.DateTimeField(verbose_name="可交易生效时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "ordering": ["-market_effective_time", "-event_time"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "symbol", "market_effective_time"],
                        name="api_event_user_id_1e4c49_idx",
                    ),
                    models.Index(
                        fields=["user_id", "symbol", "event_time"],
                        name="api_event_user_id_8b09ec_idx",
                    ),
                ],
            },
        ),
    ]
