# Generated by Django 5.0.6 on 2025-12-21 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_ai_model_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="当前使用的 AI 模型配置ID"
            ),
        ),
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="deepseek",
                        max_length=50,
                        null=True,
                        verbose_name="AI Provider",
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        default="https://api.deepseek.com",
                        max_length=255,
                        null=True,
                        verbose_name="AI Base URL",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        default="deepseek-chat",
                        max_length=50,
                        null=True,
                        verbose_name="AI Model",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="AI API Key"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "updated_at"],
                        name="api_aimodel_user_id_fec44a_idx",
                    )
                ],
                "unique_together": {("user_id", "provider", "base_url", "model")},
            },
        ),
    ]
