# Generated by Django 5.0.6 on 2025-12-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_userprofile_active_ai_model_id_aimodelconfig"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aimodelconfig",
            unique_together={("user_id", "provider", "base_url", "model", "api_key")},
        ),
    ]
